### ISSUE TITLE
Crashing when crop

### ISSUE THREAD

**Issue by swapneshp-spaceo** [jaiobs/OptiVideoEditor-for-iOS#3]
when we try to crop the video so at that time app is crashing, please check

**Comment by jams032** [comment]
@swapneshp-spaceo  , getting same issue. Let us know if you have found the fix.

**Comment by jams032** [comment]
@swapneshp-spaceo , i migrated to another slider and it fixed my problem that helps me not to waste much time.  Using uiview from storyboard as IBOUTLET seems much easier approach rather than the declarative approach for RangeSlider.

**Comment by RakeshImpinge** [comment]
Hii @jaiobs1 @jams032 
I have implement this library in my app, but i am getting crash while cropping the video using slider,  i have also download your code and got crash, so when we expect your crash free code on git.
Can you please also provide me other solution for fix this crash.
thank you!

**Comment by jams032** [comment]
@RakeshImpinge , read my last comment. This was solution from my side.

**Comment by RakeshImpinge** [comment]
As you mentioned above Using uiview from storyboard as IBOUTLET seems easier approach rather than the,
Do I need to assign any class to Uiview? If yes then which class we need to assign o uiview?

**Comment by RakeshImpinge** [comment]
Could you please share the your Fixed Source code because its urgent for me.
Thank you!

**Comment by RakeshImpinge** [comment]
@jams032  Please help me about this.

**Comment by benchama55** [comment]
> Hii @RakeshImpinge
can you please give code source with error fixed , i try what u say but no result ,i'm beginner.
thanks

**Comment by adeelpervaiz** [comment]
getting same error and random crashes. even if applied one filter you can't change to another, it will give error.

**Comment by wesoo** [comment]
Getting the same error.

**Comment by rizwan78629** [comment]
Finally! the solution is, just change the argument name of the method being called in the `addTarget` on rangeSlider value change.

**Comment by suresh-mobileteam** [comment]
Hello all, the issue was covered and check this commit 0e07e2a.
