### ISSUE TITLE
Portrait video saved in Landscape mode

### ISSUE THREAD

**Issue by vitthalAnpat** [jaiobs/OptiVideoEditor-for-iOS#4]
After adding sticker to portrait video then video get saved in Landscape mode.

Please let me know is there any solution to fix this.

**Comment by suresh-mobileteam** [comment]
Hello @vitthalAnpat, the issue was covered and check this commit https://github.com/jaiobs/OptiVideoEditor-for-iOS/pull/7/commits/0e07e2a0c5254f4f761dfe93aaaa3213e6404b35.
